name: app-vulnerableApplication CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fortify_sast:
   name: Fortify SAST
   uses: evernowbr/actions-toolkit/.github/workflows/SCAN-Fortify-terra.yml@main
   with:
     appVersion: ${{ github.ref_name }}
     repositoryName: ${{ github.event.repository.name }}
     appLanguage: "other"
     enableFortifyExclusions: true
     runs_on: self-hosted
   secrets:
     FORTIFY_SSC_TOKEN: ${{ secrets.FORTIFY_SSC_TOKEN }}
     FORTIFY_UNIFIED_LOGIN_TOKEN: ${{ secrets.FORTIFY_UNIFIED_LOGIN_TOKEN }}
     FORTIFY_SSC_API_URL: ${{ secrets.FORTIFY_SSC_API_URL }}
     FORTIFY_CONTROLLER_URL: ${{ secrets.FORTIFY_CONTROLLER_URL }}
     FORTIFY_CONTROLLER_TOKEN: ${{ secrets.FORTIFY_CONTROLLER_TOKEN }}
     
  dependency_track:
    name: SCA (Dependency-Track)
    uses: evernowbr/actions-toolkit/.github/workflows/SCA-terra.yml@main
    with:
      appVersion: ${{ github.ref_name }}
      repositoryName: ${{ github.event.repository.name }}
    secrets:
      DEPENDENCY_TRACK_TOKEN: ${{ secrets.DEPENDENCY_TRACK_TOKEN }}
